### ISSUE TITLE
Ibeacon sometimes can't notify me '- (void)locationManager:(CLLocationManager *)manager didExitRegion:(CLRegion *)region'

### ISSUE THREAD

**Issue by huzhongyin** [lgaches/BeaconEmitter#15]
Hello：
When I test my app，I found that '- (void)locationManager:(CLLocationManager *)manager didExitRegion: (CLRegion *)region', this method was not executed sometimes,nearly ten percent .Do you know why is it ?
Thank you very much!!!

**Comment by lgaches** [comment]
@huzhongyin this issue is not related to BeaconEmitter. I recommend looking at Apple's documentation.
https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate/1423630-locationmanager
