### ISSUE TITLE
Persist user's entered UUID, Major, and Minor values

### ISSUE THREAD

**Issue by ScottG489** [lgaches/BeaconEmitter#23]
After restarting the app these values seem to be reset/regenerated.

Reasoning is that for a given device, these values should not change so that the device can be properly identified by other devices.

**Comment by lgaches** [comment]
Thanks for the feedback. I plan to integrate a history of the beacon settings.

**Comment by lgaches** [comment]
fixed by https://github.com/lgaches/BeaconEmitter/commit/911496315657acac3fd43bedd2989f0452a7ace2
