### ISSUE TITLE
TestFlight "not available in your country or region"

### ISSUE THREAD

**Issue by ScottG489** [lgaches/BeaconEmitter#25]
Trying to set this up on a new computer, but after I click on the app store link I get this error:
```
This app is currently not available in your country or region.
```
Maybe I'm not remembering how to open this in TestFlight?

**Comment by ScottG489** [comment]
I just restarted my laptop and I'm actually not able to run it either. I think you need to refresh something in TestFlight. Or if you have an invitation code?

**Comment by ScottG489** [comment]
Hey, sorry I know I'm being a bother, but I'm just wondering if you've had a chance to look at this? This tool was really valuable for me to use for room detection and my setup has kinda fallen apart without it :(

**Comment by lgaches** [comment]
Apple rejected the app. A new Testflight build will be available in the next 24h.

**Comment by ScottG489** [comment]
Thanks for getting back to me. That's too bad. Was it something resolvable or did they not like the core concept of the app.

Also would it be possible for you to release some kind of artifact that can be installed independently of Testflight? That way you won't need to keep publishing it on Testflight whenever it expires on there.

**Comment by lgaches** [comment]
`Your app uses public APIs in an unapproved manner,`.

As the app is free and developed during my personal time, I prefer not to invest efforts in dealing with the Apple approval process. Instead, I will explore the process of building the app and making it accessible on GitHub.

**Comment by lgaches** [comment]
@ScottG489 https://github.com/lgaches/BeaconEmitter/releases/download/1.0.0/BeaconEmitter.app.zip
